version: "3.9"

services:
  test-web:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/code
    ports:
      - "8000:8000"
#        command: gunicorn app.buyandsell.wsgi:application --bind 0.0.0.0:8000 --workers 3
    command: python ./app/manage.py runserver 0.0.0.0:8000
    # command: python
    # tty: true

networks:
  default:
    external:
      name: test_exante_default
